name: global_defense_insight
description: "A new Flutter project."
#

publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.6.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  get: ^4.7.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true

  assets:
    - assets/animations/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
