name: global_defense_insight
description: "A new Flutter project."
#

publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.6.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  get: ^4.7.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.1
  iconsax: ^0.0.8
  flutter_keyboard_visibility: ^6.0.0
  firebase_core: ^3.15.2
  google_sign_in: ^6.1.6
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_easyloading: ^3.0.5
  firebase_messaging: ^15.2.4
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  image_card: ^0.0.4
  shared_preferences: ^2.2.2
  google_nav_bar: ^5.0.7
  get_storage: ^2.1.1
  http: ^1.4.0
  intl: ^0.20.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
