// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5P-fZtiyGZR0owJDntzOQV4RUGqIUAs',
    appId: '1:716950428247:web:a1336641d1b93618e0a112',
    messagingSenderId: '716950428247',
    projectId: 'global-defense-insight',
    authDomain: 'global-defense-insight.firebaseapp.com',
    storageBucket: 'global-defense-insight.firebasestorage.app',
    measurementId: 'G-FH1HH9P9GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpp0KfGNwmBL3QYiw4iuxigxigacaF-Bo',
    appId: '1:716950428247:android:eb4ce57ee3e2b87ae0a112',
    messagingSenderId: '716950428247',
    projectId: 'global-defense-insight',
    storageBucket: 'global-defense-insight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCovYNyzXe_Rg6oGsdh7P5_Sx0X-wsc4J4',
    appId: '1:716950428247:ios:b746f5cdab4a734ce0a112',
    messagingSenderId: '716950428247',
    projectId: 'global-defense-insight',
    storageBucket: 'global-defense-insight.firebasestorage.app',
    iosBundleId: 'com.example.globalDefenseInsight',
  );
}
